# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

services:
  pigfarmmanagementapi:
    image: pigfarmmanagementapi
    build:
      context: .
      dockerfile: PigFarmManagement.Api/Dockerfile
      args:
        - configuration=Debug
    ports:
      - 5017:5017
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - ~/.vsdbg:/remote_debugger:rw
