# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

services:
  pigfarmmanagementapi:
    image: pigfarmmanagementapi
    build:
      context: .
      dockerfile: PigFarmManagement.Api/Dockerfile
    ports:
      - 5017:5017
